spring:
  application:
    name: restaurant-onboarding
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_onboarding
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
